# Generated by Django 5.0.4 on 2024-05-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_item_created_by_shop_item_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='item-images'),
        ),
    ]
