# Generated by Django 4.2.12 on 2024-05-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('item', '0006_remove_item_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shop',
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shop.shop'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
