# Generated by Django 4.2.12 on 2024-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_remove_item_shop_category_shop_delete_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item-images'),
        ),
    ]
