# Generated by Django 4.2.12 on 2024-05-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
